---
- hosts: webserver
  tasks:
    - name: Task - 1 Update APT package manager repositories cache
      become: true
      yum:
        update_cache: yes
    - name: Task -2 Install Java using Ansible
      become: yes
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - java-1.8.0-openjdk
