- name: tomcat installation
  hosts: webserver
  become: yes
  tasks:
    - name: Install java8
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: download tomcat9
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
        dest: /opt/
    - name: check /opt/tomcat9 folder is present
      stat:
        path: /opt/tomcat9
      register: st
    - name: extract the file
      unarchive:
        src: /opt/apache-tomcat-9.0.62.tar.gz
        dest: /opt/tomcat9
        remote_src: True
        owner: ec2-user
        group: ec2-user
      when: not st.stat.exists
    
